name: Aerial Drone Videography and Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58944
title: Aerial Drone Videography and Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b507c'
    - '#00c1e7'
    - '#000000'
    - '#fefef9'
    - '#99a3ab'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
